name: CI/CD

on:
  push:
    branches:
      - lab8

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v2
      - run: dart pub get
      - run: dart analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v2
      - run: dart pub get
      - run: dart test

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v2
      - run: flutter pub get
      - run: flutter build web --release

  deploy: # Deploy your web app (example using Firebase Hosting)
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - uses: actions/checkout@v3
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      - run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
      - run: gcloud auth activate-service-account --key-file=service-account-key.json
      - run: gcloud firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
      - run: gcloud firebase hosting:site:deploy public --project ${{ secrets.FIREBASE_PROJECT_ID }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v2
      - run: flutter pub get
      - run: flutter build windows --release
